# Site settings
facebook: 1500652936893411
title:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cobertura.brasildefato.com.br/"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'gulpfile.js']

collections:
